#docker-compose up --build -d   ->for rebuilding the image
#docker exec -it f802f5556bf2  redis-cli -> to access the redis-cli

services:


  go-backend:                     # Service name 
    build: ./backend                # Build the image using the Dockerfile in the 'backend' directory
    expose: 
      - 8080         # Expose port 8080 in the container, so that backend can accesss it internally
    deploy:
      replicas: 2                 # Automatically creates multiple servers at 8080
      restart_policy:
        condition: on-failure
    networks:
       - app-network


  nginx-load-balancer:  
    image: nginx:latest  
    ports:
      - "8080:80"        # Host:8080 -> Nginx:80  HOST_PORT:CONTAINER_PORT
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf    #copy the nginx.conf file to the container
    depends_on:
      - go-backend  # Ensure the backend is running before starting Nginx
    networks:
      - app-network

  redis:
   image: redis:latest
   container_name: redis_cache
   restart: always
   ports:
      - "6379:6379"
   networks:
      - app-network


networks:
  app-network:
    driver: bridge  
