# Build stage
FROM golang:1.24 AS builder  
WORKDIR /backend

# Copy dependency files first for better caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the source code
COPY . . 

# Build the Go binary
RUN CGO_ENABLED=0 GOOS=linux go build -o main .


# Run stage
FROM alpine:3.18  
WORKDIR /backendrun        

# Copy the binary from the builder stage
COPY --from=builder /backend/main .

# Copy the .env file
COPY .env .env

# Ensure the binary is executable
RUN chmod +x ./main  

# Add a non-root user
RUN adduser -D sunitwiz
USER sunitwiz


# Run the application
CMD ["./main"]
