// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CodeFile struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

type GeneratedCode struct {
	Files      []*CodeFile `json:"files"`
	IsComplete bool        `json:"isComplete"`
	Chunk      *string     `json:"chunk,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUpInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Subscription struct {
}

type User struct {
	ID        string  `json:"id"`
	Username  string  `json:"username"`
	Email     string  `json:"email"`
	IsActive  *bool   `json:"isActive,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}
